function [x_list,y_list,overlap]=areaScanSetup
% Interactive GUI for tiling image for area scanning
% Outputs lists of center x,y coordinates for each image
    fig = uifigure('Name','Image Tiler','Position',[100 100 1000 600]);
    
	ax = uiaxes(fig,'Position',[20 20 560 560],...
        'XLim',[0 300],'YLim', [0 300],'DataAspectRatio',[1 1 1]);
    
    lens_info_panel = uipanel(fig,'Position',[600 400 310 130]);
    f_tube_label = uilabel(lens_info_panel,...
        'Position',[10 100 200 20],...
        'Text','Focal length of tube lens (mm)');
    f_tube_dd = uidropdown(lens_info_panel,...
        'Position',[210 100 90 20],...
        'Items',{'100','150','180','200'},...
        'ItemsData',[100 150 180 200],...
        'Value',100);
    f_obj_label = uilabel(lens_info_panel,...
        'Position',[10 70 200 20],...
        'Text','Focal length of objective lens (mm)');
    f_obj_dd = uidropdown(lens_info_panel,...
        'Position',[210 70 90 20],...
        'Items',{'100','150','180','200'},...
        'ItemsData',[100 150 180 200],...
        'Value',200);
    mag_obj_label = uilabel(lens_info_panel,...
        'Position',[10 40 200 20],...
        'Text','Objective lens magnification');
    mag_obj_field = uieditfield(lens_info_panel, 'numeric','Value',1,...
        'Position',[210 40 90 20],'Limits',[1 100]);
    total_mag_label = uilabel(lens_info_panel,...
        'Position',[10 10 200 20],...
        'Text','Total magnification');
    total_mag_field = uieditfield(lens_info_panel, 'numeric',...
        'Position',[210 10 90 20],...
        'Editable','off',...
        'Value',0);
    
    % These callbacks must be defined after all referenced fields have been
    % created.
    f_tube_dd.ValueChangedFcn = @(f_tube_dd,event) updatemagnification(...
        total_mag_field,mag_obj_field,f_obj_dd,f_tube_dd);
    f_obj_dd.ValueChangedFcn = @(f_obj_dd,event) updatemagnification(...
        total_mag_field,mag_obj_field,f_obj_dd,f_tube_dd);
    mag_obj_field.ValueChangedFcn = @(mab_obj_field,event) updatemagnification...
        (total_mag_field,mag_obj_field,f_obj_dd,f_tube_dd);
    updatemagnification(total_mag_field,mag_obj_field,f_obj_dd,f_tube_dd);
    
 
    dimensions_panel = uipanel(fig,'Position',[600 200 310 160]);
    sensor_h_label = uilabel(dimensions_panel,...
        'Position',[10 130 200 20],...
        'Text','Camera sensor height (mm)');
    sensor_h_field = uieditfield(dimensions_panel, 'numeric','Value',4.6,...
        'Position',[210 130 90 20],'Limits',[0 100]);
    sensor_w_label = uilabel(dimensions_panel,...
        'Position',[10 100 200 20],...
        'Text','Camera sensor width (mm)');
    sensor_w_field = uieditfield(dimensions_panel, 'numeric','Value',6.4,...
        'Position',[210 100 90 20],'Limits',[0 100]);
    area_h_label = uilabel(dimensions_panel,...
        'Position',[10 70 200 20],...
        'Text','Height of scanning area (mm)');
    area_h_field = uieditfield(dimensions_panel, 'numeric','Value',150,...
        'Position',[210 70 90 20],'Limits',[1 10000]);
    area_w_label = uilabel(dimensions_panel,...
        'Position',[10 40 200 20],...
        'Text','Width of scanning area (mm)');
    area_w_field = uieditfield(dimensions_panel, 'numeric','Value',150,...
        'Position',[210 40 90 20],'Limits',[1 10000]);
    overlap_label = uilabel(dimensions_panel,...
        'Position',[10 10 200 20],...
        'Text','Overlap between images (%)');
    overlap_field = uieditfield(dimensions_panel, 'numeric','Value',10,...
        'Position',[210 10 90 20],'Limits',[0 100]);
    
    nrows_label = uilabel(fig,...
        'Position',[740 165 140 20],...
        'Text','Number of rows');
    nrows_field = uieditfield(fig, 'numeric',...
        'Position',[860 165 50 20],...
        'Editable','off',...
        'Value',0);
    ncols_label = uilabel(fig,...
        'Position',[740 140 140 20],...
        'Text','Number of columns');
    ncols_field = uieditfield(fig, 'numeric',...
        'Position',[860 140 50 20],...
        'Editable','off',...
        'Value',0);
    nimages_label = uilabel(fig,...
        'Position',[740 115 140 20],...
        'Text','Number of images');
    nimages_field = uieditfield(fig, 'numeric',...
        'Position',[860 115 50 20],...
        'Editable','off',...
        'Value',0);
    
    updatebtn = uibutton(fig,...
        'ButtonPushedFcn',@(updatebtn,event) areaScanPreview(...
        ax,area_h_field.Value,area_w_field.Value,sensor_h_field.Value,...
        sensor_w_field.Value,f_tube_dd.Value,f_obj_dd.Value,...
        mag_obj_field.Value,overlap_field.Value,nrows_field,ncols_field,...
        nimages_field),...
        'Position',[620 150 100 35],...
        'Text',{'Update','preview'},...
        'HorizontalAlignment','center',...
        'VerticalAlignment','center');
    
    donebtn = uibutton(fig,...
        'ButtonPushedFcn',@(donebtn,event) togglegoodness,...
        'Position',[620 110 100 30],...
        'Text','Done',...
        'HorizontalAlignment','center',...
        'VerticalAlignment','center');
    
    global allgood
    allgood=false;
    while ~allgood
        pause(0.1)
    end
    
    if allgood
        [x_list,y_list] = areaScanPreview(...
            ax,area_h_field.Value,area_w_field.Value,sensor_h_field.Value,...
            sensor_w_field.Value,f_tube_dd.Value,f_obj_dd.Value,...
            mag_obj_field.Value,overlap_field.Value,nrows_field,ncols_field,...
            nimages_field);
        overlap=overlap_field.Value/100;
        closereq;
    else
        x_list = NaN;
        y_list = NaN;
    end
    
    function togglegoodness
        allgood=~allgood;
    end
end