
%%
    fig = uifigure('Name','Registration Preview','Position',[100 100 1000 600]);
    
	ax = uiaxes(fig,'Position',[20 20 560 560],...
        'XLim',[0 300],'YLim', [0 300]);
    
    label_pos = [630 400 160 20];
    spacing = 30;
    field_pos = [label_pos(1)+label_pos(3)+spacing label_pos(2) 80 20];
    sensor_h_label = uilabel(fig,'Position',label_pos,...
        'Text','Camera sensor height (mm)');
    sensor_h_field = uieditfield(fig, 'numeric','Value',4.6,...
        'Position',field_pos,'Limits',[0 100]);
    sensor_w_label = uilabel(fig,'Position',label_pos+[0 -1*spacing 0 0],...
        'Text','Camera sensor width (mm)');
    sensor_w_field = uieditfield(fig, 'numeric','Value',6.4,...
        'Position',field_pos+[0 -1*spacing 0 0],'Limits',[0 100]);
    f_tube_label = uilabel(fig,'Position',label_pos+[0 -2*spacing 0 0],...
        'Text','Focal length of tube lens (mm)');
    f_tube_field = uidropdown(fig,...
        'Position',field_pos+[0 -2*spacing 0 0],...
        'Items',{'100','150','180','200'},...
        'ItemsData',[100 150 180 200],...
        'Value',100);
%     f_tube_field = uieditfield(fig, 'numeric','Value',100,...
%         'Position',field_pos+[0 -2*spacing 0 0],'Limits',[1 400]);
    f_obj_label = uilabel(fig,'Position',label_pos+[0 -3*spacing 0 0],...
        'Text','Focal length of objective lens (mm)');
    f_obj_field = uidropdown(fig,...
        'Position',field_pos+[0 -3*spacing 0 0],...
        'Items',{'100','150','180','200'},...
        'ItemsData',[100 150 180 200],...
        'Value',200);
    mag_obj_label = uilabel(fig,'Position',label_pos+[0 -4*spacing 0 0],...
        'Text','Objective lens magnification');
    mag_obj_field = uieditfield(fig, 'numeric','Value',1,...
        'Position',field_pos+[0 -4*spacing 0 0],'Limits',[1 100]);
    area_h_label = uilabel(fig,'Position',label_pos+[0 -5*spacing 0 0],...
        'Text','Height of scanning area (mm)');
    area_h_field = uieditfield(fig, 'numeric','Value',150,...
        'Position',field_pos+[0 -5*spacing 0 0],'Limits',[1 10000]);
    area_w_label = uilabel(fig,'Position',label_pos+[0 -6*spacing 0 0],...
        'Text','Width of scanning area (mm)');
    area_w_field = uieditfield(fig, 'numeric','Value',150,...
        'Position',field_pos+[0 -6*spacing 0 0],'Limits',[1 10000]);
    overlap_label = uilabel(fig,'Position',label_pos+[0 -7*spacing 0 0],...
        'Text','Overlap between images (%)');
    overlap_field = uieditfield(fig, 'numeric','Value',10,...
        'Position',field_pos+[0 -7*spacing 0 0],'Limits',[0 100]);
    
    sensor_height = sensor_h_field.Value;
    sensor_width = sensor_w_field.Value;
    f_tube = f_tube_field.Value;
    f_obj = f_obj_field.Value;
    mag_obj = mag_obj_field.Value;
    area_height = area_h_field.Value;
    area_width = area_w_field.Value;
    overlap = overlap_field.Value/100;
    
total_mag = mag_obj * (f_tube / f_obj);
image_height = sensor_height / total_mag;
image_width = sensor_width / total_mag;

n_rows = ceil(area_height/(image_height*(1+overlap)));
n_cols = ceil(area_width/(image_width*(1+overlap)));

x_0 = (image_width/2)-(image_width*overlap);
x_end = (area_width-(image_width/2))+(image_width*overlap);
y_0 = (image_height/2)-(image_height*overlap);
y_end = (area_height-(image_height/2))+(image_height*overlap);

xs = linspace(x_0,x_end,n_cols);
ys = linspace(y_0,y_end,n_rows);

[x_list,y_list] = meshgrid(xs,ys);

    updatebtn = uibutton(fig,...
        'ButtonPushedFcn',@(updatebtn,event) areaScanPreview(ax,area_h_field.Value,area_w_field.Value,sensor_h_field.Value,sensor_w_field.Value,f_tube_field.Value,f_obj_field.Value,mag_obj_field.Value,overlap_field.Value),...
        'Position',[10 5 180 55],...
        'FontSize',14,...
        'Text',{'Update','preview'},...
        'HorizontalAlignment','center');
    